Support for signed_commits
schubergphilis/terraform-github-mcaf-repository pull request #39
Opened 2021-12-08 10:07 UTC by dennisbrouwer91

2021-12-08 10:09 UTC, shoekstra requested changes

2021-12-08 10:09 UTC, shoekstra commented on variables.tf
> +  description = "Boolean to enable or disable signed commits requirement"
```suggestion
  description = "Boolean to require signed commits"
```

2021-12-08 10:11 UTC, marwinbaumannsbp commented on variables.tf
> +variable "require_signed_commits" {
Should this not be part of the branch_protection variable?

2021-12-08 10:16 UTC, shoekstra commented on variables.tf
> +variable "require_signed_commits" {
Good catch 👍  I believe it should as it's used in the `github_branch_protection` resource.

2021-12-08 12:09 UTC, marwinbaumannsbp commented on main.tf
> +  require_signed_commits = local.protection[count.index].require_signed_commits
You have to change the local as well :-)

2021-12-08 13:06 UTC, marwinbaumannsbp submitted a review, later dismissed
Make sure to create a new tag according to semantic versioning and make sure its tagged as a breaking change version

2021-12-09 07:57 UTC, shoekstra submitted a review, later dismissed

2021-12-09 07:58 UTC, shoekstra commented
> Make sure to create a new tag according to semantic versioning and make sure its tagged as a breaking change version

And by this, `0.4.0` 😉

2021-12-09 08:04 UTC, svanharmelen requested changes

2021-12-09 08:04 UTC, svanharmelen commented on main.tf
> +        require_signed_commits = config.require_signed_commits
Please use correct alphabetical ordering (goes for all locations of course):
```suggestion
        branch                 = branch
        enforce_admins         = config.enforce_admins
        push_restrictions      = config.push_restrictions
        require_signed_commits = config.require_signed_commits
        required_reviews       = config.required_reviews
        required_checks        = config.required_checks
```

2021-12-09 08:26 UTC, svanharmelen submitted a review, later dismissed

2021-12-09 09:17 UTC, svanharmelen approved these changes

2021-12-09 09:20 UTC, merged